force-app/main/default/objects/Training_Program__c/Training_Program__c.object-meta.xml
<CustomObject>
    <label>Training Program</label>
    <nameField>
        <label>Training Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Program__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Livelli di skill del programma di tennis</description>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Entry</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Low</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Medium</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>High</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Professional</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Preparing</fullName>
                <default>true</default>
                <label>Preparing</label>
            </value>
            <value>
                <fullName>Designed</fullName>
            </value>
            <value>
                <fullName>Doing</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training_Program__c/recordTypes/Public.recordType-meta.xml
<RecordType>
    <fullName>Public</fullName>
    <active>true</active>
    <description>Training program svolto con più di 1 partecipante fino ad un massimo di 3</description>
    <label>Public</label>
</RecordType>

force-app/main/default/objects/Tutor__c/Tutor__c.object-meta.xml
<CustomObject>
    <label>Tutor</label>
    <nameField>
        <label>Nome Tutor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tutors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tutor__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tutor__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Tutor__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Tutor__c/fields/Seniority_Level__c.field-meta.xml
<CustomField>
    <fullName>Seniority_Level__c</fullName>
    <label>Seniority Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Entry</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tutor__c/fields/Training_Program__c.field-meta.xml
<CustomField>
    <fullName>Training_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Program</label>
    <referenceTo>Training_Program__c</referenceTo>
    <relationshipLabel>Tutors</relationshipLabel>
    <relationshipName>Tutors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PTTutorAssignmentTest.cls
@isTest
public class PTTutorAssignmentTest {
    
    @TestSetup
    static void testSetupData(){
        List<Training_Program__c> pts=new List<Training_Program__c>();
        List<Tutor__c> tutors=new List<Tutor__c>();
        for(Integer i=1;i<=5;i++){
            Training_Program__c ptTest = new Training_Program__c(Level__c=''+i,Name='Test '+i,Status__c='Preparing');
            Tutor__c tutorTest = new Tutor__c(Seniority_Level__c=''+i, Available__c=true, First_Name__c='First name Test '+i
                                            , Last_Name__c='Last name test '+i,name='Test '+i);
            pts.add(ptTest);
            tutors.add(tutorTest);    
        }
        insert pts;
        insert tutors;
    }
    
    @isTest
    static void testStatusDesigned(){
        //retriving data
        List<Training_Program__c> pts=[SELECT Id, Level__c, Name, Status__c, 
                                             (SELECT Id, Seniority_Level__c, Training_Program__c, Available__c, Name, First_Name__c, Last_Name__c FROM Tutors__r)
                                             FROM Training_Program__c];
        Test.startTest();
        List<Training_Program__c> ptsChangingStatus=new List<Training_Program__c>();
        for(Training_Program__c pt : pts){
            pt.Status__c='Designed';
            ptsChangingStatus.add(pt);
        }
        update ptsChangingStatus;
        Test.stopTest();
        List<Training_Program__c> verifyPts=[SELECT Id, Level__c, Name, Status__c, 
                                             (SELECT Id, Seniority_Level__c, Training_Program__c, Available__c, Name, First_Name__c, Last_Name__c FROM Tutors__r)
                                             FROM Training_Program__c];
        for(Training_Program__c pt : verifyPts){
            System.assertEquals(pt.Tutors__r[0].Seniority_Level__c, pt.Level__c, 'ERROR');
        }
    }
    
    @isTest
    static void testStatusDone(){
        //retriving data
        List<Training_Program__c> pts=[SELECT Id, Level__c, Name, Status__c, 
                                             (SELECT Id, Seniority_Level__c, Training_Program__c, Available__c, Name, First_Name__c, Last_Name__c FROM Tutors__r)
                                             FROM Training_Program__c];
        List<Tutor__c> tutors=[SELECT Id, Seniority_Level__c, Training_Program__c, Available__c, Name, First_Name__c, Last_Name__c FROM Tutor__c];
        //Matching tutor before test the unmatching
        List<Tutor__c> tutorsDesigned= new List<Tutor__c>();
        List<Training_Program__c> ptsDesigned= new List<Training_Program__c>();
        for(Training_Program__c pt: pts){
            pt.Status__c='Designed';
            ptsDesigned.add(pt);
        }
        update ptsDesigned;
        //Testing unmatching
        Test.startTest();
        List<Tutor__c> tutorsUnmatched=new List<Tutor__c>();
        List<Training_Program__c> ptsDoneStatus=new List<Training_Program__c>();
        for(Training_Program__c pt : pts){
            pt.Status__c='Done';
            ptsDoneStatus.add(pt);
        }
        update ptsDoneStatus;
        Test.stopTest();
        List<Training_Program__c> verifyPts=[SELECT Id, Level__c, Name, Status__c, 
                                             (SELECT Id, Seniority_Level__c, Training_Program__c, Available__c, Name, First_Name__c, Last_Name__c FROM Tutors__r)
                                             FROM Training_Program__c];
        List<Tutor__c> verifyTutorsUnmatched=[SELECT Id, Seniority_Level__c, Training_Program__c, Available__c, Name, First_Name__c, Last_Name__c FROM Tutor__c];
        for(Training_Program__c pt : verifyPts){
            System.assertEquals(pt.Tutors__r.size(),0, 'ERROR - ci sono tutor assegnati');
        	for(Tutor__c tutor : verifyTutorsUnmatched){
            	System.assertEquals(tutor.Training_Program__c,null, 'ERROR - ci sono tutor assegnati');
            	System.assertEquals(tutor.Available__c,true, 'ERROR - ci sono tutor che risultano non disponibili');
        	}
        }
    }
    
    @isTest
    static void testNullException(){
        //retriving data
        List<Training_Program__c> pts=[SELECT Id, Level__c, Name, Status__c, 
                                             (SELECT Id, Seniority_Level__c, Training_Program__c, Available__c, Name, First_Name__c, Last_Name__c FROM Tutors__r)
                                             FROM Training_Program__c];
        List<Tutor__c> tutors=[SELECT Id, Seniority_Level__c, Training_Program__c, Available__c, Name, First_Name__c, Last_Name__c FROM Tutor__c];
        List<Tutor__c> tutorsNotAvailable=new List<Tutor__c>();
        for(Tutor__c tutor :tutors){
            tutor.Available__c=false;
            tutorsNotAvailable.add(tutor);
        }
        update tutorsNotAvailable;
        //Test
        Test.startTest();
        List<Training_Program__c> ptsChangingStatus=new List<Training_Program__c>();
        for(Training_Program__c pt : pts){
            pt.Status__c='Designed';
            ptsChangingStatus.add(pt);
        }
        Database.SaveResult[] result = Database.update(ptsChangingStatus, false);
        Test.stopTest();
        List<Training_Program__c> verifyPts=[SELECT Id, Level__c, Name, Status__c, 
                                             (SELECT Id, Seniority_Level__c, Training_Program__c, Available__c, Name, First_Name__c, Last_Name__c FROM Tutors__r)
                                             FROM Training_Program__c];
        for(Training_Program__c pt : verifyPts){
            System.assertEquals(pt.Tutors__r.size(), 0, 'ERROR');
        }
    }
}