force-app/main/default/objects/Trainee__c/Trainee__c.object-meta.xml
<CustomObject>
    <label>Trainee</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainee__c/fields/Email_address__c.field-meta.xml
<CustomField>
    <fullName>Email_address__c</fullName>
    <label>Email address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Trainee__c/fields/Training_program_feedback__c.field-meta.xml
<CustomField>
    <fullName>Training_program_feedback__c</fullName>
    <label>Training program feedback</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trainee__c/fields/Vote__c.field-meta.xml
<CustomField>
    <fullName>Vote__c</fullName>
    <label>Vote</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VoteFeedbackMail.cls
public with sharing class EmailManager {
    @InvocableMethod (label='SendMail'description ='Return mail with feedback and vote' category ='Trainee_c')
    public static void sendFeedbackEmail(List<Trainee__c> feedbackInputs){
        feedbackInputs = [SELECT ID, Training_program_feedback__c, Vote__c FROM Trainee__c];
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

        for (Trainee__c IterateFeedback : feedbackInputs) {
            Id Trainee = Trainee__c.Id;
            Integer Vote = Trainee__c.Vote__c;
            String Feedback = Trainee__c.Training_program_feedback__c;

            Trainee__c getTraineeEmail = [SELECT Email_address__c FROM Trainee__c WHERE Id = :Trainee__c.Id LIMIT 1];
            String TraineeEmail = Trainee__c.Email_address__c;

            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

            email.setToAddresses(new List<String>{ TraineeEmail });

            email.setSubject('Feedback sul programma di training');

            String emailBody = 'Ciao';
            emailBody += 'Grazie per aver lasciato un feedback al nostro programma di training.';
            emailBody += 'Il tuo voto è: ' + Vote + '/10\n\n';
            emailBody += 'Grazie ancora e ci auguriamo di vederti presto per il prossimo programma di training!';
            emailBody += 'Cordiali saluti,';
            emailBody += 'Tennis World';

            email.setPlainTextBody(emailBody);

            emails.add(email);
          
        }

        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { emails });
    }
}